services:
  currency_convertor:
    build:
      dockerfile: ./Dockerfile
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "3333"
    ports:
      - "3333:3333"

